# Site settings
title: Program Management Playbook
name: Program Management Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Program Management Guidance
baseurl: '/ficam-management'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-management/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: ficam-management
  description: FICAM Playbook - Program Management Guidance
  url: https://github.com/gsa/program-guides

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Step 1 - Establish Program Governance
  url: 1_step-1
  internal: true
  coll: false
- text: Step 2 - Establish Project Management Office
  url: 2_step-2
  internal: true
  coll: false
- text: Step 3 - Establish Work streams
  url: 3_step-3
  internal: true
  coll: false
- text: Step 4 - Develop ICAM Program Communications Plan
  url: 4_step-4
  internal: true
  coll: false
- text: Step 5 - Identify Program Stakeholders
  url: 5_step-5
  internal: true
  coll: false
- text: Step 6 - Manage Stakeholders
  url: 6_step-6
  internal: true
- text: Step 7 - Establish ICAM Privacy Requirements 
  url: 7_step-7
  internal: true
- text: Step 8 - Manage Program Risk 
  url: 8_step-8
  internal: true
- text: Step 9 - Conduct Capital Planning for ICAM
  url: 9_step-9
  internal: true
- text: Step 10 - Plan and Conduct Acquisition
  url: 10_step-10
  internal: true
- text: Step 11 - Measure and Report Performance 
  url: 11_step-11
  internal: true
- text: Step 12 - Manage Accountability and Control  
  url: 12_step-12
  internal: true
- text: Contribute
  url: contribute
  internal: true

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
