# Site settings
title: Program Management Playbook
name: Program Management Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Program Management Guidance
highlighter: rouge
repo_url: https://github.com/gsa/program-guides
baseurl: '/ficam-management'
branch: master
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-management/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
#- title: Federal ICAM Architecture
#  description: Federal ICAM Architecture
#  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
- title: Federal PKI Guides
  description: Federal PKI Guides
  url: https://fpki.idmanagement.gov

# Put the information about your site's GitHub repository if it is public
repo_url: https://github.com/gsa/program-guides

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Establish Program Governance
  url: program-govern
  internal: true
  coll: false
- text: Establish Project Management Office
  url: pmo
  internal: true
  coll: false
- text: Establish Workstreams
  url: workstreams
  internal: true
  coll: false
- text: Develop ICAM Program Communications Plan
  url: comm-plan
  internal: true
  coll: false
- text: Identify Program Stakeholders
  url: id-stakeholders
  internal: true
  coll: false
- text: Manage Stakeholders
  url: manage-stakeholders
  internal: true
- text: Establish ICAM Privacy Requirements
  url: privacy-require
  internal: true
- text: Manage Program Risk
  url: prog-risk
  internal: true
- text: Conduct Capital Planning for ICAM
  url: capital-plan
  internal: true
- text: Plan and Conduct Acquisition
  url: acquis
  internal: true
- text: Measure and Report Performance
  url: perform
  internal: true
- text: Manage Accountability and Control
  url: accountability
  internal: true
- text: Contribute
  url: contribute
  internal: true

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
