# Site settings
title: Program Management Playbook
name: Program Management Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Program Management Guidance
highlighter: rouge
repo_url: https://github.com/gsa/program-guides
baseurl: '/ficam-management'
branch: master
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-management/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
#- title: Federal ICAM Architecture
#  description: Federal ICAM Architecture
#  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
- title: Federal PKI Guides
  description: Federal PKI Guides
  url: https://fpki.idmanagement.gov

# Put the information about your site's GitHub repository if it is public
repo_url: https://github.com/gsa/program-guides

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Program Management Playbook
  url: pm-playbook
  internal: true
  coll: true
  collname: pm-playbook
- text: Contribute
  url: contribute
  internal: true
  coll: false


  #https://github.com/jekyll/jekyll/issues/2346
#- text: Developer Guides
#  url: devconfig/index/
#  internal: true
#  coll: true
#  collname: devconfig
#- text: User Guides
#  url: userconfig/index/
#  internal: true
#  coll: true
#  collname: userconfig

collections:
  pm-playbook:
    label: "Program Management Playbook"
    permalink: /pm-playbook/:path/
    output: true

  #https://github.com/jekyll/jekyll/issues/2346

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
